[android]
sdk=D:/android-sdk
ndk=${android:sdk}/ndk/${defaults:ndk_version}
cmake=${android:sdk}/cmake/${defaults:cmake_version}/bin/cmake.exe
ninja=${android:sdk}/cmake/${defaults:cmake_version}/bin/ninja.exe
d8=${android:sdk}/build-tools/${defaults:build_tools_version}/d8.bat

[java]
java_home=%USERPROFILE%/.jdks/temurin-${defaults:java_version}

[kotlin]
kotlin_home=C:/Program Files/kotlinc

[rust]
cargo=C:/Users/sasha/.cargo/bin/cargo.exe
rustc=C:/Users/sasha/.rustup/toolchains/stable-x86_64-pc-windows-msvc/bin/rustc.exe
cargo_ndk=C:/Users/sasha/.cargo/bin/cargo-ndk.exe
rustup=C:/Users/sasha/.cargo/bin/rustup.exe

[defaults]
# armeabi-v7a or arm64-v8a or x86 or x86_64
default_abi=x86_64
ndk_version=29.0.14206865
cmake_version=4.1.2
java_version=25.0.1
min_sdk=21
build_tools_version=36.1.0
platform_version=android-36
